apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dinoarchive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lauuwu/dinoarchive-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: dinoarchive-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: dinoarchive-config
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dinoarchive-config
                  key: DB_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dinoarchive-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dinoarchive-secret
                  key: SECRET_KEY
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: dinoarchive-secret
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dinoarchive-secret
                  key: SMTP_PASSWORD
            - name: UPLOAD_DIR
              value: "/app/uploads"
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):5432/$(POSTGRES_DB)
          volumeMounts:
            - name: gallery-storage
              mountPath: /app/uploads
      volumes:
        - name: gallery-storage
          persistentVolumeClaim:
            claimName: gallery-pvc
