"""
Seed completo de los 30 dinosaurios de DinoArchive.
Incluye datos científicos verificados con fuentes atribuidas.

IMPORTANTE: este script REEMPLAZA todos los dinosaurios existentes.
Antes de correrlo, vaciá la tabla para evitar duplicados:

    kubectl exec -it deployment/postgres -n dinoarchive -- \\
        psql -U dino -d dinoarchive -c "TRUNCATE TABLE dinosaurs CASCADE;"

Uso:
    python3 seed_dinos_full.py
"""

import json
import urllib.request
import urllib.error

API_BASE = "http://dinoarchive.local:8080"

DINOS = [
    {
        "name": "Tyrannosaurus Rex",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "12",
        "description": "El depredador terrestre más icónico de la historia, con una mordida capaz de triturar huesos y sentidos extremadamente desarrollados. Dominó los ecosistemas de Norteamérica durante los últimos 2 millones de años del Cretácico.",
        "fun_fact": "Sus brazos medían apenas 1 metro pero podían levantar más de 200 kg cada uno.",
        "family": "Tyrannosauridae",
        "clade": "Terópodo",
        "epoch": "Cretácico tardío, 68–66 Ma",
        "country": "Estados Unidos, Canadá",
        "continent": "América del Norte",
        "weight_t": "8.0",
        "locomotion": "bípedo",
        "discovered_year": 1874,
        "discoverer": "Edward Drinker Cope",
        "institution": "American Museum of Natural History (AMNH), New York",
        "source": "Osborn, H.F. (1905). Tyrannosaurus and other Cretaceous carnivorous dinosaurs. Bulletin of the AMNH, 21(14)."
    },
    {
        "name": "Velociraptor",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "2",
        "description": "Pequeño depredador emplumado de Asia central con una garra retráctil en cada pie. Inteligente y ágil, probablemente cazaba en grupos coordinados presas más grandes que él.",
        "fun_fact": "En realidad medía apenas 60 cm de alto y estaba cubierto de plumas, muy diferente a su versión cinematográfica.",
        "family": "Dromaeosauridae",
        "clade": "Terópodo",
        "epoch": "Cretácico tardío, 75–71 Ma",
        "country": "Mongolia, China",
        "continent": "Asia",
        "weight_t": "0.015",
        "locomotion": "bípedo",
        "discovered_year": 1923,
        "discoverer": "Peter Kaisen (expedición de H.F. Osborn)",
        "institution": "American Museum of Natural History (AMNH), New York",
        "source": "Osborn, H.F. (1924). Three new Theropoda, Protoceratops zone, central Mongolia. American Museum Novitates, 144."
    },
    {
        "name": "Stegosaurus",
        "period": "Jurásico",
        "diet": "herbívoro",
        "length_m": "9",
        "description": "Herbívoro de gran tamaño con dos filas de placas óseas dérmicas en el lomo y una cola armada con cuatro espinas afiladas (thagomizer). Sus placas estaban irrigadas de sangre y probablemente servían para regular temperatura y señalización visual.",
        "fun_fact": "A pesar de medir 9 metros, su cerebro era del tamaño de una nuez de macadamia.",
        "family": "Stegosauridae",
        "clade": "Tireóforo / Estegosaurio",
        "epoch": "Jurásico tardío, 155–150 Ma",
        "country": "Estados Unidos (Colorado, Utah, Wyoming)",
        "continent": "América del Norte",
        "weight_t": "5.3",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1877,
        "discoverer": "Othniel Charles Marsh",
        "institution": "Peabody Museum of Natural History, Yale University",
        "source": "Marsh, O.C. (1877). A new order of extinct Reptilia (Stegosauria) from the Jurassic of the Rocky Mountains. American Journal of Science, 14."
    },
    {
        "name": "Triceratops",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "9",
        "description": "Uno de los dinosaurios con cuernos más reconocibles, con tres cuernos faciales y un gran escudo óseo (frill) que podía medir hasta 1 metro. Vivió en manadas en los bosques y llanuras del oeste de Norteamérica.",
        "fun_fact": "Fósiles de Triceratops con marcas de mordidas de T. Rex demuestran que ambos interactuaban directamente.",
        "family": "Ceratopsidae",
        "clade": "Ceratopsio",
        "epoch": "Cretácico tardío, 68–66 Ma",
        "country": "Estados Unidos (Montana, Wyoming, Dakota del Sur)",
        "continent": "América del Norte",
        "weight_t": "12.0",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1887,
        "discoverer": "John Bell Hatcher (bajo dirección de O.C. Marsh)",
        "institution": "Smithsonian Institution / U.S. Geological Survey",
        "source": "Marsh, O.C. (1889). Notice of gigantic horned Dinosauria from the Cretaceous. American Journal of Science, 38."
    },
    {
        "name": "Diplodocus",
        "period": "Jurásico",
        "diet": "herbívoro",
        "length_m": "26",
        "description": "Uno de los dinosaurios más largos conocidos gracias a su cuello y cola extremadamente elongados. Usaba la cola como látigo supersónico para defensa. Sus fosas nasales estaban ubicadas en la parte superior del cráneo.",
        "fun_fact": "La punta de su cola podía romper la barrera del sonido al chasquearla, generando un estampido audible a gran distancia.",
        "family": "Diplodocidae",
        "clade": "Saurópodo",
        "epoch": "Jurásico tardío, 154–152 Ma",
        "country": "Estados Unidos (Colorado, Utah, Wyoming, Montana)",
        "continent": "América del Norte",
        "weight_t": "16.0",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1877,
        "discoverer": "Samuel Wendell Williston (bajo dirección de O.C. Marsh)",
        "institution": "Peabody Museum of Natural History, Yale University",
        "source": "Marsh, O.C. (1878). Principal characters of American Jurassic dinosaurs. American Journal of Science, 16."
    },
    {
        "name": "Allosaurus",
        "period": "Jurásico",
        "diet": "carnívoro",
        "length_m": "12",
        "description": "El gran depredador del Jurásico tardío de Norteamérica. Con una mandíbula superior capaz de abrirse a casi 80°, usaba la cabeza como un hacha para desgarrar presas. Evidencia fósil sugiere comportamiento gregario.",
        "fun_fact": "Su mandíbula podía abrirse casi 80 grados, más que cualquier cocodrilo moderno.",
        "family": "Allosauridae",
        "clade": "Terópodo",
        "epoch": "Jurásico tardío, 155–145 Ma",
        "country": "Estados Unidos (Utah, Colorado, Wyoming), Portugal",
        "continent": "América del Norte, Europa",
        "weight_t": "2.3",
        "locomotion": "bípedo",
        "discovered_year": 1869,
        "discoverer": "Ferdinand Vandiveer Hayden",
        "institution": "U.S. Geological Survey / Peabody Museum of Natural History",
        "source": "Marsh, O.C. (1877). Notice on a new and gigantic dinosaur. American Journal of Science, 14."
    },
    {
        "name": "Ankylosaurus",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "10",
        "description": "El dinosaurio acorazado por excelencia. Cubierto de placas óseas (osteodermos) incluso en los párpados, rematado por una maza caudal capaz de fracturar los huesos de un Tyrannosaurus. Era tan pesado que era casi imposible voltearlo.",
        "fun_fact": "Su maza caudal podía pesar más de 60 kg y fracturar el fémur de un T. Rex de un solo golpe.",
        "family": "Ankylosauridae",
        "clade": "Tireóforo / Anquilosaurio",
        "epoch": "Cretácico tardío, 68–66 Ma",
        "country": "Estados Unidos (Montana), Canadá (Alberta)",
        "continent": "América del Norte",
        "weight_t": "6.0",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1906,
        "discoverer": "Peter Kaisen (expedición de B. Brown)",
        "institution": "American Museum of Natural History (AMNH), New York",
        "source": "Brown, B. (1908). The Ankylosauridae, a new family of armored dinosaurs from the Upper Cretaceous. Bulletin of the AMNH, 24."
    },
    {
        "name": "Pteranodon",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "1.8",
        "description": "El reptil volador más grande de Norteamérica durante el Cretácico, con una envergadura de hasta 7 metros. Técnicamente no era un dinosaurio sino un pterosaurio. Se alimentaba de peces buceando como un pelícano, sin un solo diente.",
        "fun_fact": "A pesar de su enorme tamaño, pesaba apenas 20–25 kg gracias a sus huesos huecos.",
        "family": "Pteranodontidae",
        "clade": "Pterosaurio (no es un dinosaurio)",
        "epoch": "Cretácico tardío, 86–84 Ma",
        "country": "Estados Unidos (Kansas, Nebraska, South Dakota)",
        "continent": "América del Norte",
        "weight_t": "0.025",
        "locomotion": "volador / cuadrúpedo en tierra",
        "discovered_year": 1870,
        "discoverer": "Othniel Charles Marsh",
        "institution": "Peabody Museum of Natural History, Yale University",
        "source": "Marsh, O.C. (1876). Notice of a new sub-order of Pterosauria. American Journal of Science, 11."
    },
    {
        "name": "Compsognathus",
        "period": "Jurásico",
        "diet": "carnívoro",
        "length_m": "1",
        "description": "Uno de los dinosaurios no aviares más pequeños conocidos, del tamaño de un pollo moderno. Bípedo, veloz y ágil, cazaba lagartijas e insectos en las costas del mar de Tetis. Sus fósiles se conservaron en calizas de grano fino que revelaron restos de su última comida.",
        "fun_fact": "Un famoso fósil conservó en su estómago los huesos de una lagartija (Bavarisaurus) que había devorado.",
        "family": "Compsognathidae",
        "clade": "Terópodo",
        "epoch": "Jurásico tardío, 150 Ma",
        "country": "Alemania, Francia",
        "continent": "Europa",
        "weight_t": "0.0008",
        "locomotion": "bípedo",
        "discovered_year": 1859,
        "discoverer": "Johann A. Wagner",
        "institution": "Bayerische Staatssammlung für Paläontologie und Geologie, Múnich",
        "source": "Wagner, J.A. (1859). Über einige im lithographischen Schiefer neu aufgefundene Schildkröten und Saurier. Sitzungsberichte der Bayerischen Akademie der Wissenschaften."
    },
    {
        "name": "Parasaurolophus",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "10",
        "description": "Hadrosaurio famoso por su larga cresta ósea tubular y hueca que se extendía hacia atrás desde la cabeza. Actuaba como una cámara de resonancia que amplificaba los llamados del animal. Vivía en manadas y era probable presa habitual de grandes terópodos.",
        "fun_fact": "Investigadores de la Universidad de New Mexico recrearon digitalmente su llamado: sonaba como un cuerno grave y profundo.",
        "family": "Hadrosauridae",
        "clade": "Ornitópodo / Hadrosaurio",
        "epoch": "Cretácico tardío, 76–73 Ma",
        "country": "Canadá (Alberta), Estados Unidos (Nuevo México, Utah)",
        "continent": "América del Norte",
        "weight_t": "2.5",
        "locomotion": "bípedo/cuadrúpedo",
        "discovered_year": 1921,
        "discoverer": "William Parks",
        "institution": "Royal Ontario Museum, Toronto",
        "source": "Parks, W.A. (1922). Parasaurolophus walkeri, a new species of trachodont dinosaur. University of Toronto Studies, Geological Series, 13."
    },
    {
        "name": "Yutyrannus huali",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "9",
        "description": "El animal emplumado más grande conocido en la historia de la vida en la Tierra. Pariente lejano del T. Rex, vivió en climas más fríos del noreste de China. Sus plumas filamentosas lo cubrían completamente, evidenciando que las plumas en tirannosauroídeos evolucionaron mucho antes de lo pensado.",
        "fun_fact": "Su nombre significa 'tirano emplumado hermoso' en latín y chino mandarín combinados.",
        "family": "Proceratosauridae",
        "clade": "Terópodo / Tirannosauroídeo",
        "epoch": "Cretácico temprano, 125 Ma",
        "country": "China (provincia de Liaoning)",
        "continent": "Asia",
        "weight_t": "1.4",
        "locomotion": "bípedo",
        "discovered_year": 2012,
        "discoverer": "Xu Xing et al.",
        "institution": "Institute of Vertebrate Paleontology and Paleoanthropology (IVPP), Beijing",
        "source": "Xu, X. et al. (2012). A gigantic feathered dinosaur from the Lower Cretaceous of China. Nature, 484, 92–95."
    },
    {
        "name": "Spinosaurus",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "15",
        "description": "El dinosaurio carnívoro más largo conocido, con adaptaciones semiacuáticas únicas: patas traseras cortas, pies con membranas y huesos densos para nadar. Cazaba peces gigantes en los ríos del norte de África, similar a un cocodrilo moderno gigante.",
        "fun_fact": "Estudios de densidad ósea de 2020 (Universidad de Milán) confirman que pasaba más tiempo en el agua que en tierra.",
        "family": "Spinosauridae",
        "clade": "Terópodo / Espinosáurido",
        "epoch": "Cretácico tardío, 99–93 Ma",
        "country": "Egipto, Marruecos",
        "continent": "África",
        "weight_t": "7.0",
        "locomotion": "cuadrúpedo/bípedo",
        "discovered_year": 1912,
        "discoverer": "Richard Markgraf",
        "institution": "Bayerische Staatssammlung für Paläontologie und Geologie (descripto por E. Stromer)",
        "source": "Stromer, E. (1915). Ergebnisse der Forschungsreisen Prof. E. Stromers in den Wüsten Ägyptens. Abhandlungen der Bayerischen Akademie der Wissenschaften."
    },
    {
        "name": "Giganotosaurus",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "12",
        "description": "El mayor terópodo carnívoro del hemisferio sur, ligeramente más largo que el T. Rex aunque con un cerebro más pequeño. Cazaba titanosaurios como el Argentinosaurus en las llanuras de la Patagonia. Su cráneo medía más de 1.8 metros.",
        "fun_fact": "Fue descubierto por un mecánico rural, Rubén Carolini, en 1993 mientras manejaba por el desierto patagónico.",
        "family": "Carcharodontosauridae",
        "clade": "Terópodo",
        "epoch": "Cretácico tardío, 99–97 Ma",
        "country": "Argentina (provincia de Neuquén)",
        "continent": "América del Sur",
        "weight_t": "6.5",
        "locomotion": "bípedo",
        "discovered_year": 1993,
        "discoverer": "Rubén Carolini",
        "institution": "Universidad Nacional del Comahue / Museo Carmen Funes, Plaza Huincul",
        "source": "Coria, R.A. & Salgado, L. (1995). A new giant carnivorous dinosaur from the Cretaceous of Patagonia. Nature, 377, 224–226."
    },
    {
        "name": "Brachiosaurus",
        "period": "Jurásico",
        "diet": "herbívoro",
        "length_m": "22",
        "description": "Saurópodo con una postura única: sus patas delanteras eran más largas que las traseras, dándole una inclinación hacia adelante que le permitía alcanzar follaje a 12+ metros de altura. Su enorme corazón debía bombear sangre a una cabeza muy elevada.",
        "fun_fact": "Se estima que su corazón pesaba alrededor de 400 kg para bombear sangre hasta tan alto.",
        "family": "Brachiosauridae",
        "clade": "Saurópodo / Titanosauriforme",
        "epoch": "Jurásico tardío, 154–150 Ma",
        "country": "Estados Unidos (Colorado), Tanzania",
        "continent": "América del Norte, África",
        "weight_t": "56.0",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1900,
        "discoverer": "Elmer Riggs",
        "institution": "Field Museum of Natural History, Chicago",
        "source": "Riggs, E.S. (1903). Structure and relationships of opisthocoelian dinosaurs. Publications of the Field Columbian Museum, Geological Series, 2."
    },
    {
        "name": "Iguanodon",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "10",
        "description": "Uno de los primeros dinosaurios en describirse científicamente (1825) y el tercero en recibir un nombre válido. Su pulgar cónico se identificó inicialmente como cuerno nasal. Podía caminar tanto en dos como en cuatro patas y tenía baterías dentales para procesar vegetación dura.",
        "fun_fact": "Cuando se encontraron los primeros fósiles en 1822, los científicos creyeron que el pulgar espinoso era el cuerno de la nariz.",
        "family": "Iguanodontidae",
        "clade": "Ornitópodo",
        "epoch": "Cretácico temprano, 126–122 Ma",
        "country": "Bélgica, Reino Unido, Alemania, España",
        "continent": "Europa",
        "weight_t": "3.0",
        "locomotion": "bípedo/cuadrúpedo",
        "discovered_year": 1822,
        "discoverer": "Gideon Mantell (fósiles); Mary Ann Mantell (posiblemente los primeros dientes)",
        "institution": "Natural History Museum, Londres",
        "source": "Mantell, G.A. (1825). Notice on the Iguanodon, a newly discovered fossil reptile. Philosophical Transactions of the Royal Society, 115."
    },
    {
        "name": "Pachycephalosaurus",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "4.5",
        "description": "El dinosaurio de cráneo más grueso conocido, con un domo óseo de hasta 25 cm de espesor. Estudios histológicos muestran que el domo seguía creciendo con la edad. Vivió en los mismos ecosistemas que el T. Rex en el oeste de Norteamérica.",
        "fun_fact": "Su nombre significa 'lagarto de cabeza gruesa', y el domo craneal era tan sólido que resistía golpes que habrían fracturado cualquier otro cráneo.",
        "family": "Pachycephalosauridae",
        "clade": "Marginocéfalo / Paquicefalosaurio",
        "epoch": "Cretácico tardío, 70–66 Ma",
        "country": "Estados Unidos (Montana, Wyoming, Dakota del Sur)",
        "continent": "América del Norte",
        "weight_t": "0.45",
        "locomotion": "bípedo",
        "discovered_year": 1931,
        "discoverer": "Donald Baird & John R. Horner (descripción formal en 1943 por Brown & Schlaikjer)",
        "institution": "American Museum of Natural History (AMNH), New York",
        "source": "Brown, B. & Schlaikjer, E.M. (1943). A study of the troödont dinosaurs with the description of a new genus and four new species. Bulletin of the AMNH, 82."
    },
    {
        "name": "Carnotaurus",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "8",
        "description": "Terópodo sudamericano único por sus dos cuernos sobre los ojos (el nombre significa 'toro carnívoro') y sus brazos atrofiados, más cortos incluso que los del T. Rex. Su fósil conservó impresiones de piel, revelando escamas grandes no superpuestas.",
        "fun_fact": "El único fósil conocido conservó impresiones de piel en gran parte del cuerpo, revelando una textura de escamas grandes y cónicas únicas en terópodos.",
        "family": "Abelisauridae",
        "clade": "Terópodo / Abelisáurido",
        "epoch": "Cretácico tardío, 72–70 Ma",
        "country": "Argentina (provincia de Chubut, Patagonia)",
        "continent": "América del Sur",
        "weight_t": "1.35",
        "locomotion": "bípedo",
        "discovered_year": 1984,
        "discoverer": "José Bonaparte",
        "institution": "Museo Argentino de Ciencias Naturales 'Bernardino Rivadavia', Buenos Aires",
        "source": "Bonaparte, J.F., Novas, F.E. & Coria, R.A. (1990). Carnotaurus sastrei Bonaparte, the horned, lightly built carnosaur from the Middle Cretaceous of Patagonia. Contributions in Science, Natural History Museum of Los Angeles County, 416."
    },
    {
        "name": "Brontosaurus",
        "period": "Jurásico",
        "diet": "herbívoro",
        "length_m": "22",
        "description": "Saurópodo icónico cuyo nombre fue invalidado en 1903 al confundirlo con Apatosaurus, y restaurado como género válido en 2015 tras un análisis exhaustivo de 477 especímenes. Tenía un cuello relativamente corto para un saurópodo de su tamaño.",
        "fun_fact": "El estudio de 2015 que restauró su nombre analizó 477 especímenes y tomó 5 años de investigación.",
        "family": "Diplodocidae",
        "clade": "Saurópodo / Diplodocídeo",
        "epoch": "Jurásico tardío, 156–146 Ma",
        "country": "Estados Unidos (Colorado, Oklahoma, Utah, Wyoming)",
        "continent": "América del Norte",
        "weight_t": "15.0",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1879,
        "discoverer": "Othniel Charles Marsh",
        "institution": "Peabody Museum of Natural History, Yale University",
        "source": "Tschopp, E., Mateus, O.V. & Benson, R.B.J. (2015). A specimen-level phylogenetic analysis and taxonomic revision of Diplodocidae. PeerJ, 3:e857."
    },
    {
        "name": "Therizinosaurus",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "10",
        "description": "El terópodo más extraño conocido: patas largas, cuerpo voluminoso, cuello elongado y las garras más largas de cualquier animal conocido (hasta 1 metro). A pesar de pertenecer al grupo de los terópodos (principalmente carnívoros), era herbívoro, usando sus garras para atraer ramas hacia su boca.",
        "fun_fact": "Sus garras de 1 metro eran tan grandes que cuando se encontraron los primeros fósiles en 1948, se creyó que eran costillas de una tortuga gigante.",
        "family": "Therizinosauridae",
        "clade": "Terópodo / Maniraptor / Terizinosauroídeo",
        "epoch": "Cretácico tardío, 70 Ma",
        "country": "Mongolia (desierto del Gobi)",
        "continent": "Asia",
        "weight_t": "5.0",
        "locomotion": "bípedo",
        "discovered_year": 1948,
        "discoverer": "Expedición Paleontológica Soviético-Mongola",
        "institution": "Paleontological Institute, Academia de Ciencias de Rusia (PIN RAS), Moscú",
        "source": "Maleev, E.A. (1954). A new turtle-like reptile in Mongolia. Priroda, 3. / Perle, A. (1982). On a new finding of the hindlimb of Therizinosaurus. Problems of the Geology of Mongolia, 2."
    },
    {
        "name": "Oviraptor",
        "period": "Cretácico",
        "diet": "omnívoro",
        "length_m": "2",
        "description": "Pequeño terópodo emplumado con un pico óseo sin dientes, famoso por haber sido injustamente acusado durante décadas de robar huevos ajenos. Un fósil de 1993 lo encontró sentado sobre su propio nido en posición de incubación, exonerándolo de esa acusación.",
        "fun_fact": "El nombre 'ladrón de huevos' fue un error científico que duró 70 años hasta que en 1993 un fósil lo encontró sobre su propio nido.",
        "family": "Oviraptoridae",
        "clade": "Terópodo / Oviraptorosauro",
        "epoch": "Cretácico tardío, 75–71 Ma",
        "country": "Mongolia (desierto del Gobi)",
        "continent": "Asia",
        "weight_t": "0.035",
        "locomotion": "bípedo",
        "discovered_year": 1923,
        "discoverer": "Roy Chapman Andrews (expedición del AMNH)",
        "institution": "American Museum of Natural History (AMNH), New York",
        "source": "Osborn, H.F. (1924). Three new Theropoda, Protoceratops zone, central Mongolia. American Museum Novitates, 144. / Norell, M.A. et al. (1994). A theropod dinosaur embryo and the affinities of the Flaming Cliffs dinosaur eggs. Science, 266."
    },
    {
        "name": "Deinonychus",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "3",
        "description": "El dinosaurio que cambió para siempre la percepción científica de estos animales. Su descripción en 1969 por John Ostrom impulsó la 'Revolución de los dinosaurios', demostrando que eran activos, ágiles y posiblemente endotérmicos. Su estrecha relación con las aves replanteó toda la filogenia.",
        "fun_fact": "Su descubrimiento en 1969 desencadenó la 'Revolución de los dinosaurios', cambiando su imagen de lentos reptiles a animales ágiles y posiblemente de sangre caliente.",
        "family": "Dromaeosauridae",
        "clade": "Terópodo / Dromaeosáurido",
        "epoch": "Cretácico temprano, 115–108 Ma",
        "country": "Estados Unidos (Montana, Wyoming, Oklahoma, Maryland)",
        "continent": "América del Norte",
        "weight_t": "0.07",
        "locomotion": "bípedo",
        "discovered_year": 1964,
        "discoverer": "John Ostrom",
        "institution": "Yale Peabody Museum of Natural History",
        "source": "Ostrom, J.H. (1969). Osteology of Deinonychus antirrhopus, an unusual theropod from the Lower Cretaceous of Montana. Peabody Museum Bulletin, 30."
    },
    {
        "name": "Microraptor",
        "period": "Cretácico",
        "diet": "carnívoro",
        "length_m": "1",
        "description": "El único dinosaurio no aviar con cuatro alas emplumadas, capaz de planear entre los árboles de los bosques del Cretácico chino. Estudios de sus melanosomas fosilizados revelaron que sus plumas tenían un brillo iridiscente negro azulado, como el de un cuervo.",
        "fun_fact": "El análisis de sus melanosomas fosilizados reveló que sus plumas brillaban como las de un cuervo, siendo uno de los primeros dinosaurios en que se determinó el color real.",
        "family": "Dromaeosauridae",
        "clade": "Terópodo / Microrraptorino",
        "epoch": "Cretácico temprano, 125–120 Ma",
        "country": "China (provincia de Liaoning)",
        "continent": "Asia",
        "weight_t": "0.001",
        "locomotion": "planeador / bípedo",
        "discovered_year": 2000,
        "discoverer": "Xu Xing et al.",
        "institution": "Institute of Vertebrate Paleontology and Paleoanthropology (IVPP), Beijing",
        "source": "Xu, X. et al. (2003). Four-winged dinosaurs from China. Nature, 421, 335–340. / Li, Q. et al. (2012). Reconstruction of Microraptor and the evolution of iridescent plumage. Science, 335."
    },
    {
        "name": "Edmontosaurus",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "12",
        "description": "Uno de los hadrosaurios más grandes y comunes del Cretácico tardío de Norteamérica. Sus baterías dentales contenían hasta 1000 dientes en renovación constante para procesar vegetación dura. Un espécimen momificado conservó piel, músculos y tendones.",
        "fun_fact": "Un fósil momificado encontrado en Wyoming conservó piel, músculo deshidratado y tendones, permitiendo calcular que pesaba un 25% más que lo estimado por los huesos.",
        "family": "Hadrosauridae",
        "clade": "Ornitópodo / Hadrosaurio",
        "epoch": "Cretácico tardío, 73–66 Ma",
        "country": "Canadá (Alberta), Estados Unidos (Montana, Wyoming, Alaska)",
        "continent": "América del Norte",
        "weight_t": "4.0",
        "locomotion": "bípedo/cuadrúpedo",
        "discovered_year": 1892,
        "discoverer": "John Bell Hatcher",
        "institution": "Smithsonian Institution / Carnegie Museum of Natural History, Pittsburgh",
        "source": "Lambe, L.M. (1920). The hadrosaur Edmontosaurus from the Upper Cretaceous of Alberta. Memoir of the Geological Survey of Canada, 120."
    },
    {
        "name": "Camarasaurus",
        "period": "Jurásico",
        "diet": "herbívoro",
        "length_m": "18",
        "description": "El saurópodo más común de la Formación Morrison de Norteamérica y uno de los mejor documentados del Jurásico. Sus vértebras estaban atravesadas por grandes cavidades huecas (cámaras, de ahí su nombre) que reducían el peso sin sacrificar resistencia.",
        "fun_fact": "Es el dinosaurio más común encontrado en la Formación Morrison, con cientos de especímenes de todas las edades, desde crías hasta adultos.",
        "family": "Camarasauridae",
        "clade": "Saurópodo / Macronario",
        "epoch": "Jurásico tardío, 155–145 Ma",
        "country": "Estados Unidos (Colorado, Utah, Wyoming, Nuevo México)",
        "continent": "América del Norte",
        "weight_t": "47.0",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1877,
        "discoverer": "Oramel Lucas (bajo dirección de Edward Drinker Cope)",
        "institution": "American Museum of Natural History (AMNH) / Carnegie Museum of Natural History",
        "source": "Cope, E.D. (1877). On a gigantic saurian from the Dakota epoch of Colorado. Palaeontological Bulletin, 25."
    },
    {
        "name": "Kentrosaurus",
        "period": "Jurásico",
        "diet": "herbívoro",
        "length_m": "5",
        "description": "Estegosáurido africano más robusto y armado que su pariente norteamericano Stegosaurus. Además de placas en la parte delantera del cuerpo, tenía largas espinas afiladas en la parte posterior y en los hombros. Sus fósiles fueron rescatados de la famosa cantera de Tendaguru en Tanzania.",
        "fun_fact": "Durante la Primera Guerra Mundial, más de 250 trabajadores locales excavaron durante años para rescatar los fósiles de Tendaguru que hoy están en Berlín.",
        "family": "Stegosauridae",
        "clade": "Tireóforo / Estegosaurio",
        "epoch": "Jurásico tardío, 155–150 Ma",
        "country": "Tanzania (cantera de Tendaguru)",
        "continent": "África",
        "weight_t": "0.7",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1909,
        "discoverer": "Werner Janensch (expedición del Museum für Naturkunde)",
        "institution": "Museum für Naturkunde, Berlín",
        "source": "Hennig, E. (1915). Kentrosaurus aethiopicus. Sitzungsberichte der Gesellschaft Naturforschender Freunde zu Berlin."
    },
    {
        "name": "Plateosaurus",
        "period": "Triásico",
        "diet": "herbívoro",
        "length_m": "8",
        "description": "Uno de los primeros grandes dinosaurios herbívoros, considerado un prosaurópodo o saurodomorfo basal. Podía caminar en dos o cuatro patas. El hallazgo de decenas de esqueletos en la misma localidad en Alemania generó debate sobre si murieron juntos o fueron arrastrados por una inundación.",
        "fun_fact": "En la localidad de Trossingen (Alemania) se excavaron más de 35 esqueletos completos del mismo lugar durante décadas de excavaciones.",
        "family": "Plateosauridae",
        "clade": "Saurodomorfo basal / Prosaurópodo",
        "epoch": "Triásico tardío, 214–204 Ma",
        "country": "Alemania (Trossingen, Halberstadt), Suiza, Groenlandia",
        "continent": "Europa",
        "weight_t": "4.0",
        "locomotion": "bípedo/cuadrúpedo",
        "discovered_year": 1834,
        "discoverer": "Johann Friedrich Engelhardt",
        "institution": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
        "source": "Von Meyer, H. (1837). Mittheilung an Prof. Bronn. Neues Jahrbuch für Mineralogie, Geognosie, Geologie und Petrefakten-Kunde."
    },
    {
        "name": "Coelophysis",
        "period": "Triásico",
        "diet": "carnívoro",
        "length_m": "3",
        "description": "Uno de los dinosaurios más antiguos y mejor conocidos del Triásico tardío. Ágil y de huesos huecos (de ahí su nombre), vivía y posiblemente cazaba en grandes grupos. El sitio de Ghost Ranch en Nuevo México reveló cientos de esqueletos superpuestos en un mismo nivel estratigráfico.",
        "fun_fact": "En 1998, un cráneo de Coelophysis viajó a bordo del transbordador espacial Endeavour hasta la estación MIR, convirtiéndose en el dinosaurio que más lejos ha llegado del planeta.",
        "family": "Coelophysidae",
        "clade": "Terópodo basal",
        "epoch": "Triásico tardío, 221–196 Ma",
        "country": "Estados Unidos (Nuevo México, Arizona, Utah, Connecticut)",
        "continent": "América del Norte",
        "weight_t": "0.02",
        "locomotion": "bípedo",
        "discovered_year": 1881,
        "discoverer": "David Baldwin",
        "institution": "American Museum of Natural History (AMNH), New York",
        "source": "Cope, E.D. (1887). The dinosaurian genus Coelurus. American Naturalist, 21. / Colbert, E.H. (1989). The Triassic dinosaur Coelophysis. Museum of Northern Arizona Bulletin, 57."
    },
    {
        "name": "Dilophosaurus",
        "period": "Jurásico",
        "diet": "carnívoro",
        "length_m": "7",
        "description": "Uno de los primeros grandes terópodos del Jurásico, reconocible por sus dos crestas óseas paralelas sobre el cráneo que probablemente usaba para exhibición o reconocimiento intraespecífico. Contrariamente a lo mostrado en el cine, no tenía gola ni escupía veneno.",
        "fun_fact": "Las icónicas crestas eran tan frágiles que los científicos descartan que se usaran en combate. Probablemente eran estructuras de exhibición, como la cresta de un gallo.",
        "family": "Dilophosauridae",
        "clade": "Terópodo basal",
        "epoch": "Jurásico temprano, 193–183 Ma",
        "country": "Estados Unidos (Arizona)",
        "continent": "América del Norte",
        "weight_t": "0.4",
        "locomotion": "bípedo",
        "discovered_year": 1942,
        "discoverer": "Jesse Williams (Navajo) / Sam Welles (descripción científica)",
        "institution": "University of California Museum of Paleontology (UCMP), Berkeley",
        "source": "Welles, S.P. (1954). New Jurassic dinosaur from the Kayenta Formation of Arizona. Bulletin of the Geological Society of America, 65. / Welles, S.P. (1984). Dilophosaurus wetherilli (Dinosauria, Theropoda). Palaeontographica Abt. A, 185."
    },
    {
        "name": "Megalosaurus",
        "period": "Jurásico",
        "diet": "carnívoro",
        "length_m": "9",
        "description": "El primer dinosaurio en recibir un nombre científico válido (1824), antes de que el término 'dinosaurio' existiera. Fue descripto por William Buckland en Oxford. Durante el siglo XIX, casi cualquier terópodo europeo fue asignado erróneamente a este género, convirtiéndolo en un 'contenedor basura' taxonómico.",
        "fun_fact": "Durante más de un siglo, casi todos los dinosaurios carnívoros europeos mal identificados fueron llamados 'Megalosaurus', convirtiéndolo en el género con más especies inválidas de la historia.",
        "family": "Megalosauridae",
        "clade": "Terópodo / Tetanuro",
        "epoch": "Jurásico medio, 166 Ma",
        "country": "Reino Unido (Oxfordshire, Inglaterra)",
        "continent": "Europa",
        "weight_t": "0.7",
        "locomotion": "bípedo",
        "discovered_year": 1676,
        "discoverer": "Robert Plot (primeros restos); descripto científicamente por William Buckland en 1824",
        "institution": "University of Oxford / Oxford University Museum of Natural History",
        "source": "Buckland, W. (1824). Notice on the Megalosaurus or great Fossil Lizard of Stonesfield. Transactions of the Geological Society of London, 2(1)."
    },
    {
        "name": "Styracosaurus",
        "period": "Cretácico",
        "diet": "herbívoro",
        "length_m": "5.5",
        "description": "Ceratopsio con un elaborado escudo craneal coronado por hasta seis largas espinas y un cuerno nasal prominente. Vivió en manadas en el oeste de Norteamérica. Su nombre significa 'lagarto con púas'. Un famoso hallazgo en Alberta ('Bone Bed 42') contiene cientos de individuos juntos.",
        "fun_fact": "El 'Bone Bed 42' en Alberta, Canadá, contiene los restos de cientos de Styracosaurus en el mismo lugar, lo que sugiere que murieron en una inundación mientras migraban en manada.",
        "family": "Ceratopsidae",
        "clade": "Ceratopsio / Centrosaurino",
        "epoch": "Cretácico tardío, 75–74 Ma",
        "country": "Canadá (Alberta)",
        "continent": "América del Norte",
        "weight_t": "2.7",
        "locomotion": "cuadrúpedo",
        "discovered_year": 1913,
        "discoverer": "Charles H. Sternberg",
        "institution": "Canadian Museum of Nature, Ottawa",
        "source": "Lambe, L.M. (1913). A new genus and species of Ceratopsia from the Belly River Formation of Alberta. Ottawa Naturalist, 27."
    },
]


def main():
    created, skipped = 0, 0

    for dino in DINOS:
        payload = json.dumps(dino, ensure_ascii=False).encode("utf-8")
        req = urllib.request.Request(
            f"{API_BASE}/dinos/",
            data=payload,
            headers={"Content-Type": "application/json; charset=utf-8"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as r:
                r.read()
            created += 1
            print(f"✅ {dino['name']}")
        except urllib.error.HTTPError as e:
            body = e.read().decode()
            print(f"❌ {dino['name']}: {e.code} — {body}")
            skipped += 1

    print(f"\nListo: {created} cargados, {skipped} saltados.")


if __name__ == "__main__":
    main()
