apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dinoarchive-ingress
  namespace: dinoarchive
spec:
  ingressClassName: nginx
  rules:
    - host: dinoarchive.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
